---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux
    spec:
      # The serviceAccount is only needed for Kubernetes with RBAC
      serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      containers:
      - name: fluxd
        image: quay.io/weaveworks/flux
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        args:
        - --memcached-hostname=memcached.kube-system.svc.cluster.local
        - --memcached-timeout=100ms
        - --memcached-service=memcached
        - --git-url=git@github.com:squaremo/flux-example
        - --git-branch=gitsync
#        - --git-set-author
#        - --token=local-test-token
#        - --connect=ws://authfe.default.svc.cluster.local/api/flux
