apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/locked: "true"
    flux.weave.works/lockedMsg: Locked message goes here
    flux.weave.works/lockedUser: michael@weave.works
    flux.weave.works/tag.hello: glob:master-a*
    flux.weave.works/tag.helloworld: glob:master-*
    flux.weave.works/tag.sidecar: glob:master-*
    pointless: annotation
  name: helloworld
  namespace: hello
spec:
  minReadySeconds: 1
  replicas: 5
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/squaremo/hello_world:master-a000001
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: docker
      restartPolicy: Always
