apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.policy.locked: "true"
    flux.policy.tag: glob:*-a000002
    flux.weave.works/locked: "true"
  name: helloworld
  namespace: hello
spec:
  minReadySeconds: 1
  replicas: 5
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/squaremo/hello_world:master-a000002
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: docker
      restartPolicy: Always
