apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/tag.hello: glob:master-a*
    flux.weave.works/tag.helloworld: glob:master-a00000*
    flux.weave.works/tag.sidecar: glob:master-*
  name: helloworld
  namespace: hello
spec:
  minReadySeconds: 1
  replicas: 5
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/weaveworks/helloworld:master-a000004
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
      - name: sidecar
        image: alpine:3.6
      restartPolicy: Always
